macek-projekt/macek/macek/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('web.urls', namespace="web")),
    path('admin/', admin.site.urls),
]

macek-projekt/macek/web/urls.py
from django.urls import path
from .views import *

app_name = 'web'

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('search/', SearchForPlayer.as_view(), name="search"),
    path('player/<slug:name>', PlayerView.as_view(), name="player"),
    path('champ/<slug:name>', ChampDetail.as_view(), name="champ"),
    path('champRotation/', ChampRotation.as_view(), name="rotation"),
]

macek-projekt/macek/web/models.py
from django.conf import settings
from django.db import models
import requests

from .data import champions, champions_map

class Summoner(models.Model):
    id = models.CharField(max_length=255, primary_key=True)
    accountId = models.CharField(max_length=255)
    puuid = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    profileIconId = models.IntegerField()
    revisionDate = models.BigIntegerField()
    summonerLevel = models.IntegerField()

    @property
    def get_profile_icon(self):
        return '{}{}.png'.format(settings.LOL_ICON_URL, self.profileIconId)

    def __str__(self):
        return self.name


class League(models.Model):
    leagueId = models.CharField(max_length=255)
    leagueName = models.CharField(max_length=255)
    queueType = models.CharField(max_length=255)
    position = models.CharField(max_length=255)
    tier = models.CharField(max_length=255)
    rank = models.CharField(max_length=255)
    leaguePoints = models.IntegerField()
    wins = models.IntegerField()
    losses = models.IntegerField()
    veteran = models.BooleanField()
    inactive = models.BooleanField()
    freshBlood = models.BooleanField()
    hotStreak = models.BooleanField()
    summonerId = models.ForeignKey(Summoner, on_delete=models.CASCADE)
    summonerName = models.CharField(max_length=255)

class Champion(models.Model):
    championId = models.IntegerField()
    championLevel = models.IntegerField()
    championPoints = models.IntegerField()
    lastPlayTime = models.IntegerField()
    championPointsSinceLastLevel = models.IntegerField()
    championPointsUntilNextLevel = models.IntegerField()
    chestGranted = models.BooleanField()
    tokensEarned = models.IntegerField()
    summonerId = models.ForeignKey(Summoner, on_delete=models.CASCADE)

    @property
    def champion_data(self):
        try:
            ch = champions_map[str(self.championId)]
            return ch
        except Exception as e:
            print("CHAMP_DATA",e)
            return None

macek-projekt/macek/web/views.py
import requests
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.generic import View

from .data import champions, champions_map
from .models import *


def fetch_user_data(name):
    res = requests.get('{}lol/summoner/v4/summoners/by-name/{}?api_key={}'.format(settings.LOL_API_BASE_URL, name, settings.LOL_API_KEY))
    if res.status_code == 404:
        raise Http404

    try:
        data = res.json()
        player, created = Summoner.objects.update_or_create(id=data['id'], defaults=data,)
        player.save()
    except Exception as e:
        print(e)


def fetch_league_data(name):
    player = Summoner.objects.get(name=name)
    res = requests.get('{}lol/league/v4/positions/by-summoner/{}?api_key={}'.format(settings.LOL_API_BASE_URL, player.id, settings.LOL_API_KEY))
    if res.status_code == 404:
        raise Http404

    try:
        data = res.json()
        for l in list(data):
            l['summonerId'] = player
            obj, created = League.objects.update_or_create(leagueId=l['leagueId'], defaults=l,)
            obj.save()
    except Exception as e:
        print(e)

def fetch_user_champions(name):
    player = Summoner.objects.get(name=name)
    res = requests.get('{}lol/champion-mastery/v4/champion-masteries/by-summoner/{}?api_key={}'.format(settings.LOL_API_BASE_URL, player.id, settings.LOL_API_KEY))
    if res.status_code == 404:
        raise Http404

    try:
        data = res.json()
        for ch in list(data):
            ch['summonerId'] = player
            obj, created = Champion.objects.update_or_create(championId=ch['championId'], summonerId=player, defaults=ch,)
            obj.save()
    except Exception as e:
        print(e)

class IndexView(View):
    def get(self, request, **kwargs):
        return render(request, 'index.html')


class SearchForPlayer(View):
    def get(self, request, **kwargs):
        name = request.GET.get('name')
        try:
            Summoner.objects.get(name=name)
        except ObjectDoesNotExist:
            fetch_user_data(name)
            fetch_league_data(name)
            fetch_user_champions(name)
        finally:
            return HttpResponseRedirect(reverse('web:player', args=[name]))


class PlayerView(View):
    def get(self, request, name, **kwargs):
        try:
            player = get_object_or_404(Summoner, name=name)
            fetch_league_data(name)
            fetch_user_champions(name)
            return render(request, 'player.html', {'player': player, 'leagues': player.league_set.all(), 'champions': player.champion_set.all(), })
        except Http404:
            return render(request, 'player.html', { 'player': None })

class ChampRotation(View):
    def get(self, request, **kwargs):
        r = requests.get('{}/lol/platform/v3/champion-rotations?api_key={}'.format(settings.LOL_API_BASE_URL, settings.LOL_API_KEY))
        data = r.json()
        for key in ['freeChampionIds', 'freeChampionIdsForNewPlayers']:
            tmp = []
            for ch in data[key]:
                if str(ch) in champions_map:
                    tmp.append(champions_map[str(ch)])
            data[key] = tmp
        
        return render(request, 'rotation.html', { 'data': data })


class ChampDetail(View):
    def get(self, request, name, **kwargs):
        champ = champions[name] if name in champions else None
        players = None
        try:
            ch = list(Champion.objects.filter(championId=int(champ['key'])).order_by('-championLevel'))
            players = [ (x.summonerId, x.championLevel) for x in ch ]
        except:
            pass

        return render(request, 'champ.html', { 'champ': champ, 'players': players })

macek-projekt/macek/web/templates/champ.html
{% extends "layout.html" %}

{% block content %}
    {% if champ %}
        <div class="container">
            <div class="row">
                <div class="col-4">
                    <div class="card" style="width: 18rem;">
                        <img src="http://ddragon.leagueoflegends.com/cdn/6.24.1/img/champion/{{ champ.image.full }}">
                        <div class="card-body">
                            <h5 class="card-title">{{ champ.name }}</h5>
                        </div>
                    </div>
                </div>
                <div class="col-8">
                    {% if players %}
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Player name</th>
                                    <th scope="col">Level</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for player in players %}
                                    <tr>
                                        <th scope="row">{{ forloop.counter }}</th>
                                        <td><a href="{% url 'web:player' player.0.name %}">{{ player.0.name }}</a></td>
                                        <td>{{ player.1 }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        <h1>Žádní hráči</h1>
                    {% endif %}
                </div>
            </div>
        </div>
    {% else %}
        <div class="container">
            <h1>Champion nebyl nalezen</h1>
        </div>
    {% endif %}
{% endblock content %}

macek-projekt/macek/web/templates/index.html
{% extends "layout.html" %}


{% block content %}
<div class="container">
    Hráče lze vyhledat skrze políčko hledat v navigaci
</div>
{% endblock content %}

macek-projekt/macek/web/templates/layout.html
<!DOCTYPE html>
<html lang="cs">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>LOL Stats</title>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
            crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
            crossorigin="anonymous"></script>

    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="#">LOLS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'web:rotation' %}">Champion rotations</a>
                        </li>
                    </ul>
                    <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'web:search' %}">
                        <input class="form-control mr-sm-2" type="search" name="name" placeholder="Jméno hráče" aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Hledat</button>
                    </form>
                </div>
            </div>
        </nav>
        {% block content %}{% endblock content %}
    </body>
</html>

macek-projekt/macek/web/templates/player.html
{% extends "layout.html" %}

{% block content %}
    {% if player %}
        <div class="container">
            <div class="row">
                <div class="col-4">
                    <div class="card" style="width: 18rem;">
                        <img src="{{ player.get_profile_icon }}" class="card-img-top" alt="">
                        <div class="card-body">
                            <h5 class="card-title">{{ player.name }}</h5>
                        </div>
                    </div>
                </div>
                <div class="col-8">
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Leagues</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Champions</a>
                        </li>
                    </ul>
                    <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">leagueName</th>
                                        <th scope="col">queueType</th>
                                        <th scope="col">position</th>
                                        <th scope="col">tier</th>
                                        <th scope="col">rank</th>
                                        <th scope="col">leaguePoints</th>
                                        <th scope="col">wins</th>
                                        <th scope="col">losses</th>
                                        <th scope="col">veteran</th>
                                        <th scope="col">inactive</th>
                                        <th scope="col">freshBlood</th>
                                        <th scope="col">hotStreak</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for league in leagues %}
                                        <tr>
                                            <th scope="row">{{ forloop.counter }}</th>
                                            <td>{{ league.leagueName }}</td>
                                            <td>{{ league.queueType }}</td>
                                            <td>{{ league.position }}</td>
                                            <td>{{ league.tier }}</td>
                                            <td>{{ league.rank }}</td>
                                            <td>{{ league.leaguePoints }}</td>
                                            <td>{{ league.wins }}</td>
                                            <td>{{ league.losses }}</td>
                                            <td>{{ league.veteran }}</td>
                                            <td>{{ league.inactive }}</td>
                                            <td>{{ league.freshBlood }}</td>
                                            <td>{{ league.hotStreak }}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th scope="col">#</th>
                                        <th scope="col">championId</th>
                                        <th scope="col">championLevel</th>
                                        <th scope="col">championPoints</th>
                                        <th scope="col">lastPlayTime</th>
                                        <th scope="col">championPointsSinceLastLevel</th>
                                        <th scope="col">championPointsUntilNextLevel</th>
                                        <th scope="col">chestGranted</th>
                                        <th scope="col">tokensEarned</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for champ in champions %}
                                        <tr>
                                            <th scope="row">{{ forloop.counter }}</th>
                                            <td>
                                                {% if champ.champion_data %}
                                                    <a href="{% url 'web:champ' champ.champion_data.id %}">
                                                        <img src="http://ddragon.leagueoflegends.com/cdn/6.24.1/img/champion/{{ champ.champion_data.image.full }}">
                                                    </a>
                                                    {{ champ.champion_data.name }}
                                                {% else %}
                                                    {{ champ.championId }}
                                                {% endif %}
                                            </td>
                                            <td>{{ champ.championLevel }}</td>
                                            <td>{{ champ.championPoints }}</td>
                                            <td>{{ champ.lastPlayTime }}</td>
                                            <td>{{ champ.championPointsSinceLastLevel }}</td>
                                            <td>{{ champ.championPointsUntilNextLevel }}</td>
                                            <td>{{ champ.chestGranted }}</td>
                                            <td>{{ champ.tokensEarned }}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <div class="container">
            <h1>Hráč nebyl nalezen</h1>
        </div>
    {% endif %}
{% endblock content %}

macek-projekt/macek/web/templates/rotation.html
{% extends "layout.html" %}


{% block content %}
<div class="container">
    Rotace
    <div class="row">
        <div class="col">
            <p>freeChampionIds</p>
            <ul class="list-group">
                {% for champ in data.freeChampionIds %}
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-4">
                                <a href="{% url 'web:champ' champ.id %}">
                                    <img src="http://ddragon.leagueoflegends.com/cdn/6.24.1/img/champion/{{ champ.image.full }}">
                                </a>
                            </div>
                            <div class="col-8">
                                <div class="row">
                                    <div class="col-12">{{ champ.name }}</div>
                                    <div class="col-12">{{ champ.title }}</div>
                                    <div class="col-12">{{ champ.blurb }}</div>
                                </div>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col">
        <p>freeChampionIdsForNewPlayers</p>
            <ul class="list-group">
                {% for champ in data.freeChampionIdsForNewPlayers %}
                    <li class="list-group-item">
                        <div class="row">
                            <div class="col-4">
                                <a href="{% url 'web:champ' champ.id %}">
                                    <img src="http://ddragon.leagueoflegends.com/cdn/6.24.1/img/champion/{{ champ.image.full }}">
                                </a>
                            </div>
                            <div class="col-8">
                                <div class="row">
                                    <div class="col-12">{{ champ.name }}</div>
                                    <div class="col-12">{{ champ.title }}</div>
                                    <div class="col-12">{{ champ.blurb }}</div>
                                </div>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <p>maxNewPlayerLevel - {{ data.maxNewPlayerLevel }}</p>
    </div> 
</div>
{% endblock content %}